---
- name: Install pgPool
  apt: name={{ item }} state=installed
  with_items:
    - pgpool2

- name: Configure pgPool
  template: src={{ item }}.j2 dest=/etc/pgpool2/{{ item }} mode=0644 owner=root group=root
  with_items:
   - pcp.conf
   - pgpool.conf
   - pool_hba.conf
  notify: restart pgpool2

- name: Create pool_passwd file
  template: src={{ item }}.j2 dest=/etc/pgpool2/{{ item }} mode=0664 owner=postgres group=postgres
  with_items:
   - pool_passwd
  notify: restart pgpool2
